export type QuizChoice = { id: string; text: string; originalLabel?: string };
export type QuizQuestion = { id: string; originalNumber: number; question: string; choices: QuizChoice[]; correctChoiceId: string };
export type Quiz = { id: string; title: string; subject?: string; description?: string; sourceFilename?: string; questions: QuizQuestion[]; createdAt?: string };
export type QuizSummary = Omit<Quiz, "questions"> & { questionCount: number };
export type AnswerRecord = { questionId: string; selectedChoiceId: string; correctChoiceId: string; isCorrect: boolean };
export type ParseResult = { success: boolean; questions: QuizQuestion[]; warnings: string[]; errors: string[]; answerCount: number };
export type QuizMode = "practice" | "test";
export type AssignmentAttempt = { id: string; status: "in_progress" | "completed"; mode?: QuizMode; question_count?: number; correct_count?: number; score_percent?: number; started_at: string; completed_at?: string };
export type QuizAssignment = { id: string; quiz_id: string; label: string; token: string; created_at: string; quizzes?: { title: string; subject?: string }; attempts: AssignmentAttempt[] };
